import type {Metadata} from "next";
import "./globals.css";
import Nav from "@/app/components/_nav";
import Footer from "@/app/components/_footer";
import React from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="!scroll-smooth">
        <body className="bg-white text-black">
        <Nav/>
        {children}
        <Footer /></body>
        </html>
    );
}
